"""Core data models for Personal CFO Agent v0.1."""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Any


class ProviderLevel(str, Enum):
    LEVEL_0 = "level_0_fixture_manual_snapshot"
    LEVEL_1 = "level_1_api_contract_stub"
    LEVEL_2 = "level_2_read_only_live_connector"


class ConnectionMode(str, Enum):
    FIXTURE = "fixture_manual_snapshot"
    API_STUB = "api_contract_stub"
    LIVE_READINESS = "live_readiness_check_only"
    LIVE_READ = "live_read_only"


class WarningCode(str, Enum):
    PROVIDER_DISABLED = "PROVIDER_DISABLED"
    PROVIDER_CONFIG_MISSING = "PROVIDER_CONFIG_MISSING"
    LIVE_READ_NOT_ALLOWED = "LIVE_READ_NOT_ALLOWED"
    PROVIDER_CONNECTION_FAILED = "PROVIDER_CONNECTION_FAILED"
    PROVIDER_FETCH_FAILED = "PROVIDER_FETCH_FAILED"
    UNSUPPORTED_PROVIDER = "UNSUPPORTED_PROVIDER"
    MANUAL_SNAPSHOT_REQUIRED = "MANUAL_SNAPSHOT_REQUIRED"
    STALE_SOURCE_DATA = "STALE_SOURCE_DATA"
    MISSING_MARKET_VALUE = "MISSING_MARKET_VALUE"
    MISSING_CURRENCY = "MISSING_CURRENCY"
    ACCOUNT_ID_HASHED = "ACCOUNT_ID_HASHED"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    MANUAL_VALUE_NEEDS_REVIEW = "MANUAL_VALUE_NEEDS_REVIEW"
    STALE_MANUAL_VALUATION = "STALE_MANUAL_VALUATION"
    MISSING_VALUATION_DATE = "MISSING_VALUATION_DATE"
    INVALID_AMOUNT = "INVALID_AMOUNT"
    UNSUPPORTED_PROVIDER_MANUAL_ONLY = "UNSUPPORTED_PROVIDER_MANUAL_ONLY"
    SINGPASS_AUTOMATION_BLOCKED = "SINGPASS_AUTOMATION_BLOCKED"
    LOW_LIQUIDITY_BUFFER = "LOW_LIQUIDITY_BUFFER"
    HIGH_PROPERTY_CONCENTRATION = "HIGH_PROPERTY_CONCENTRATION"
    HIGH_LEVERAGE_EXPOSURE = "HIGH_LEVERAGE_EXPOSURE"
    FIRE_GAP_LARGE = "FIRE_GAP_LARGE"
    ASSUMPTION_NEEDS_REVIEW = "ASSUMPTION_NEEDS_REVIEW"
    SECRET_DETECTED = "SECRET_DETECTED"
    FORBIDDEN_METHOD_EXPOSED = "FORBIDDEN_METHOD_EXPOSED"
    UNOFFICIAL_API_BLOCKED = "UNOFFICIAL_API_BLOCKED"
    SDK_NOT_INSTALLED = "SDK_NOT_INSTALLED"
    WEBULL_READINESS_OK = "WEBULL_READINESS_OK"
    IBKR_HANDSHAKE_TIMEOUT = "IBKR_HANDSHAKE_TIMEOUT"
    IBKR_MANAGED_ACCOUNTS_EMPTY = "IBKR_MANAGED_ACCOUNTS_EMPTY"
    IBKR_POSITIONS_EMPTY = "IBKR_POSITIONS_EMPTY"
    IBKR_ACCOUNT_SUMMARY_EMPTY = "IBKR_ACCOUNT_SUMMARY_EMPTY"
    IBKR_ACCOUNT_FILTER_MISMATCH = "IBKR_ACCOUNT_FILTER_MISMATCH"
    IBKR_CALLBACK_TIMEOUT = "IBKR_CALLBACK_TIMEOUT"
    IBKR_API_HANDSHAKE_NOT_COMPLETED = "IBKR_API_HANDSHAKE_NOT_COMPLETED"
    IBKR_GATEWAY_CALLBACK_TIMEOUT = "IBKR_GATEWAY_CALLBACK_TIMEOUT"
    IBKR_GATEWAY_API_SETTINGS_REVIEW_REQUIRED = (
        "IBKR_GATEWAY_API_SETTINGS_REVIEW_REQUIRED"
    )
    IBKR_PORT_SESSION_TYPE_MISMATCH = "IBKR_PORT_SESSION_TYPE_MISMATCH"
    IBKR_NO_DATA_RETURNED = "IBKR_NO_DATA_RETURNED"
    IBKR_DATA_PATH_NOT_IMPLEMENTED = "IBKR_DATA_PATH_NOT_IMPLEMENTED"
    IBKR_READ_SUCCEEDED_EMPTY = "IBKR_READ_SUCCEEDED_EMPTY"
    MOOMOO_SDK_NOT_INSTALLED = "MOOMOO_SDK_NOT_INSTALLED"
    MOOMOO_OPEND_UNREACHABLE = "MOOMOO_OPEND_UNREACHABLE"
    MOOMOO_CONNECTION_FAILED = "MOOMOO_CONNECTION_FAILED"
    MOOMOO_CONTEXT_OPEN_FAILED = "MOOMOO_CONTEXT_OPEN_FAILED"
    MOOMOO_ACCOUNT_LIST_FAILED = "MOOMOO_ACCOUNT_LIST_FAILED"
    MOOMOO_ACCOUNT_LIST_EMPTY = "MOOMOO_ACCOUNT_LIST_EMPTY"
    MOOMOO_ACCOUNT_FILTER_MISMATCH = "MOOMOO_ACCOUNT_FILTER_MISMATCH"
    MOOMOO_ACCOUNT_INFO_FAILED = "MOOMOO_ACCOUNT_INFO_FAILED"
    MOOMOO_POSITION_LIST_FAILED = "MOOMOO_POSITION_LIST_FAILED"
    MOOMOO_POSITION_LIST_EMPTY = "MOOMOO_POSITION_LIST_EMPTY"
    MOOMOO_POSITIONS_EMPTY = "MOOMOO_POSITIONS_EMPTY"
    MOOMOO_CASH_QUERY_FAILED = "MOOMOO_CASH_QUERY_FAILED"
    MOOMOO_CASH_EMPTY = "MOOMOO_CASH_EMPTY"
    MOOMOO_NORMALIZATION_FAILED = "MOOMOO_NORMALIZATION_FAILED"
    MOOMOO_CALLBACK_TIMEOUT = "MOOMOO_CALLBACK_TIMEOUT"
    MOOMOO_NO_DATA_RETURNED = "MOOMOO_NO_DATA_RETURNED"
    MOOMOO_DATA_PATH_NOT_IMPLEMENTED = "MOOMOO_DATA_PATH_NOT_IMPLEMENTED"
    MOOMOO_READ_SUCCEEDED_EMPTY = "MOOMOO_READ_SUCCEEDED_EMPTY"
    MOOMOO_SDK_OUTPUT_SUPPRESSED = "MOOMOO_SDK_OUTPUT_SUPPRESSED"
    MOOMOO_READ_REQUIRES_MANUAL_REVIEW = "MOOMOO_READ_REQUIRES_MANUAL_REVIEW"
    MOOMOO_ACCOUNT_DISCOVERY_OK = "MOOMOO_ACCOUNT_DISCOVERY_OK"
    MOOMOO_ACCOUNT_DISCOVERY_FAILED = "MOOMOO_ACCOUNT_DISCOVERY_FAILED"
    MOOMOO_NO_ACCOUNT_DISCOVERED = "MOOMOO_NO_ACCOUNT_DISCOVERED"
    MOOMOO_SECURITY_FIRM_MISMATCH = "MOOMOO_SECURITY_FIRM_MISMATCH"
    MOOMOO_MARKET_FILTER_MISMATCH = "MOOMOO_MARKET_FILTER_MISMATCH"
    MOOMOO_GENERAL_SEC_ACCOUNT_REQUIRED = "MOOMOO_GENERAL_SEC_ACCOUNT_REQUIRED"
    MOOMOO_ACCOUNT_STATUS_NOT_ACTIVE = "MOOMOO_ACCOUNT_STATUS_NOT_ACTIVE"
    MOOMOO_TRDMARKET_AUTH_MISSING = "MOOMOO_TRDMARKET_AUTH_MISSING"
    MOOMOO_SELECTED_ACCOUNT_MISSING = "MOOMOO_SELECTED_ACCOUNT_MISSING"
    MOOMOO_SELECTED_ACCOUNT_HASHED = "MOOMOO_SELECTED_ACCOUNT_HASHED"
    MOOMOO_EXPLICIT_ACC_ID_SELECTED = "MOOMOO_EXPLICIT_ACC_ID_SELECTED"
    MOOMOO_SDK_DISCOVERY_ARG_UNSUPPORTED = "MOOMOO_SDK_DISCOVERY_ARG_UNSUPPORTED"
    MOOMOO_READ_REQUIRES_MANUAL_UNLOCK_REVIEW = (
        "MOOMOO_READ_REQUIRES_MANUAL_UNLOCK_REVIEW"
    )
    MOOMOO_DISCOVERY_SUCCESS_WITH_VARIANT_WARNINGS = (
        "MOOMOO_DISCOVERY_SUCCESS_WITH_VARIANT_WARNINGS"
    )
    MOOMOO_ACC_INDEX_FALLBACK_USED = "MOOMOO_ACC_INDEX_FALLBACK_USED"
    MOOMOO_ACCINFO_QUERY_FAILED = "MOOMOO_ACCINFO_QUERY_FAILED"
    MOOMOO_POSITION_QUERY_FAILED = "MOOMOO_POSITION_QUERY_FAILED"
    MOOMOO_FUNDS_DATA_EMPTY = "MOOMOO_FUNDS_DATA_EMPTY"
    MOOMOO_POSITION_DATA_EMPTY = "MOOMOO_POSITION_DATA_EMPTY"
    MOOMOO_CASH_NORMALIZATION_SHAPE_WARNING = (
        "MOOMOO_CASH_NORMALIZATION_SHAPE_WARNING"
    )
    MOOMOO_READ_CONTEXT_PROBE_OK = "MOOMOO_READ_CONTEXT_PROBE_OK"
    MOOMOO_READ_CONTEXT_PROBE_FAILED = "MOOMOO_READ_CONTEXT_PROBE_FAILED"
    MOOMOO_READ_CONTEXT_NOT_FOUND = "MOOMOO_READ_CONTEXT_NOT_FOUND"
    MOOMOO_SELECTED_READ_CONTEXT_MISSING = "MOOMOO_SELECTED_READ_CONTEXT_MISSING"
    MOOMOO_ACCINFO_QUERY_OK = "MOOMOO_ACCINFO_QUERY_OK"
    MOOMOO_POSITION_QUERY_OK = "MOOMOO_POSITION_QUERY_OK"
    MOOMOO_PARTIAL_READ_ONLY_FETCH_OK = "MOOMOO_PARTIAL_READ_ONLY_FETCH_OK"
    MOOMOO_NORMALIZED_ROWS_EMPTY = "MOOMOO_NORMALIZED_ROWS_EMPTY"
    MOOMOO_READ_ONLY_FETCH_OK = "MOOMOO_READ_ONLY_FETCH_OK"
    MOOMOO_READ_ONLY_FETCH_FAILED = "MOOMOO_READ_ONLY_FETCH_FAILED"
    TIGER_CONFIG_DIR_MISSING = "TIGER_CONFIG_DIR_MISSING"
    TIGER_CONFIG_FILE_MISSING = "TIGER_CONFIG_FILE_MISSING"
    TIGER_CONFIG_PREFLIGHT_FAILED = "TIGER_CONFIG_PREFLIGHT_FAILED"
    TIGER_CONFIG_FILE_UNREADABLE = "TIGER_CONFIG_FILE_UNREADABLE"
    TIGER_CONFIG_FILE_INSIDE_REPO = "TIGER_CONFIG_FILE_INSIDE_REPO"
    TIGER_CONFIG_FILE_TRACKED = "TIGER_CONFIG_FILE_TRACKED"
    TIGER_CONFIG_HISTORY_RISK = "TIGER_CONFIG_HISTORY_RISK"
    TIGER_CONFIG_REQUIRED_KEY_MISSING = "TIGER_CONFIG_REQUIRED_KEY_MISSING"
    TIGER_CONFIG_LOAD_FAILED = "TIGER_CONFIG_LOAD_FAILED"
    TIGER_PRIVATE_KEY_FIELD_MISSING = "TIGER_PRIVATE_KEY_FIELD_MISSING"
    TIGER_PRIVATE_KEY_FORMAT_UNKNOWN = "TIGER_PRIVATE_KEY_FORMAT_UNKNOWN"
    TIGER_PROPS_PATH_MISMATCH = "TIGER_PROPS_PATH_MISMATCH"
    TIGER_CONFIG_PREFLIGHT_OK = "TIGER_CONFIG_PREFLIGHT_OK"
    TIGER_SDK_CONFIG_PROBE_FAILED = "TIGER_SDK_CONFIG_PROBE_FAILED"
    TIGER_PROPS_PATH_MODE_FAILED = "TIGER_PROPS_PATH_MODE_FAILED"
    TIGER_PROPS_PATH_DIRECTORY_FAILED = "TIGER_PROPS_PATH_DIRECTORY_FAILED"
    TIGER_PROPS_PATH_FILE_FAILED = "TIGER_PROPS_PATH_FILE_FAILED"
    TIGER_SDK_DEFAULT_CONFIG_FAILED = "TIGER_SDK_DEFAULT_CONFIG_FAILED"
    TIGER_EXPLICIT_CONFIG_OBJECT_FAILED = "TIGER_EXPLICIT_CONFIG_OBJECT_FAILED"
    TIGER_SDK_CONFIG_CONSTRUCTED = "TIGER_SDK_CONFIG_CONSTRUCTED"
    TIGER_SDK_CLIENT_CONSTRUCTED = "TIGER_SDK_CLIENT_CONSTRUCTED"
    TIGER_SDK_EXCEPTION_SANITIZED = "TIGER_SDK_EXCEPTION_SANITIZED"
    TIGER_OFFICIAL_DIRECTORY_CONFIG_FAILED = "TIGER_OFFICIAL_DIRECTORY_CONFIG_FAILED"
    TIGER_HELPER_CONFIG_FALLBACK_USED = "TIGER_HELPER_CONFIG_FALLBACK_USED"
    TIGER_HELPER_CONFIG_FALLBACK_FAILED = "TIGER_HELPER_CONFIG_FALLBACK_FAILED"
    TIGER_CONFIG_MODE_SELECTED = "TIGER_CONFIG_MODE_SELECTED"
    TIGER_PRIVATE_KEY_MISSING = "TIGER_PRIVATE_KEY_MISSING"
    TIGER_PRIVATE_KEY_FORMAT_INVALID = "TIGER_PRIVATE_KEY_FORMAT_INVALID"
    TIGER_ACCOUNT_MISSING = "TIGER_ACCOUNT_MISSING"
    TIGER_CLIENT_INIT_FAILED = "TIGER_CLIENT_INIT_FAILED"
    TIGER_CLIENT_AUTH_FAILED = "TIGER_CLIENT_AUTH_FAILED"
    TIGER_ACCOUNT_CONTEXT_EMPTY = "TIGER_ACCOUNT_CONTEXT_EMPTY"
    TIGER_ASSETS_QUERY_FAILED = "TIGER_ASSETS_QUERY_FAILED"
    TIGER_POSITIONS_QUERY_FAILED = "TIGER_POSITIONS_QUERY_FAILED"
    TIGER_CASH_QUERY_FAILED = "TIGER_CASH_QUERY_FAILED"
    TIGER_NO_DATA_RETURNED = "TIGER_NO_DATA_RETURNED"
    TIGER_READ_SUCCEEDED_EMPTY = "TIGER_READ_SUCCEEDED_EMPTY"
    TIGER_NORMALIZATION_FAILED = "TIGER_NORMALIZATION_FAILED"
    TIGER_DATA_PATH_NOT_IMPLEMENTED = "TIGER_DATA_PATH_NOT_IMPLEMENTED"
    ACCOUNT_NAV_MISSING = "ACCOUNT_NAV_MISSING"
    ACCOUNT_NAV_DERIVED = "ACCOUNT_NAV_DERIVED"
    ACCOUNT_NAV_PROVIDER_REPORTED = "ACCOUNT_NAV_PROVIDER_REPORTED"
    ACCOUNT_NAV_RECONCILIATION_MISMATCH = "ACCOUNT_NAV_RECONCILIATION_MISMATCH"
    ACCOUNT_NAV_RECONCILIATION_OK = "ACCOUNT_NAV_RECONCILIATION_OK"
    ACCOUNT_NAV_UNAVAILABLE = "ACCOUNT_NAV_UNAVAILABLE"
    POSITION_LEDGER_BEST_EFFORT = "POSITION_LEDGER_BEST_EFFORT"
    POSITION_ROWS_MISSING = "POSITION_ROWS_MISSING"
    PROVIDER_BUNDLE_MISSING = "PROVIDER_BUNDLE_MISSING"
    PROVIDER_SCHEMA_MISMATCH = "PROVIDER_SCHEMA_MISMATCH"
    PROVIDER_SUMMARY_MISSING = "PROVIDER_SUMMARY_MISSING"
    ACCOUNT_HASH_MISSING = "ACCOUNT_HASH_MISSING"
    SYMBOL_MISSING = "SYMBOL_MISSING"
    CURRENCY_MISSING = "CURRENCY_MISSING"
    AS_OF_DATE_MISSING = "AS_OF_DATE_MISSING"
    POSSIBLE_DUPLICATE_POSITION = "POSSIBLE_DUPLICATE_POSITION"
    MARKET_VALUE_MISSING = "MARKET_VALUE_MISSING"
    COST_BASIS_MISSING = "COST_BASIS_MISSING"
    STALE_PROVIDER_BUNDLE = "STALE_PROVIDER_BUNDLE"
    MIXED_AS_OF_DATES = "MIXED_AS_OF_DATES"
    EMPTY_PROVIDER_LEDGER = "EMPTY_PROVIDER_LEDGER"
    MERGE_COMPLETED_WITH_WARNINGS = "MERGE_COMPLETED_WITH_WARNINGS"
    MERGE_COMPLETED_OK = "MERGE_COMPLETED_OK"
    DASHBOARD_V2_INPUT_MISSING = "DASHBOARD_V2_INPUT_MISSING"
    DASHBOARD_V2_ACCOUNT_NAV_LEDGER_MISSING = (
        "DASHBOARD_V2_ACCOUNT_NAV_LEDGER_MISSING"
    )
    DASHBOARD_V2_ACCOUNT_NAV_EMPTY = "DASHBOARD_V2_ACCOUNT_NAV_EMPTY"
    DASHBOARD_V2_PROVIDER_SUMMARY_MISSING = "DASHBOARD_V2_PROVIDER_SUMMARY_MISSING"
    DASHBOARD_V2_POSITION_LEDGER_MISSING = "DASHBOARD_V2_POSITION_LEDGER_MISSING"
    DASHBOARD_V2_POSITION_LEDGER_BEST_EFFORT = (
        "DASHBOARD_V2_POSITION_LEDGER_BEST_EFFORT"
    )
    DASHBOARD_V2_NAV_RECONCILIATION_WARNINGS = (
        "DASHBOARD_V2_NAV_RECONCILIATION_WARNINGS"
    )
    DASHBOARD_V2_STALE_DATA_WARNING = "DASHBOARD_V2_STALE_DATA_WARNING"
    DASHBOARD_V2_MIXED_AS_OF_DATES = "DASHBOARD_V2_MIXED_AS_OF_DATES"
    DASHBOARD_V2_GENERATED_OK = "DASHBOARD_V2_GENERATED_OK"
    DASHBOARD_V2_GENERATED_WITH_WARNINGS = "DASHBOARD_V2_GENERATED_WITH_WARNINGS"
    SNAPSHOT_INPUT_MISSING = "SNAPSHOT_INPUT_MISSING"
    SNAPSHOT_ACCOUNT_NAV_LEDGER_MISSING = "SNAPSHOT_ACCOUNT_NAV_LEDGER_MISSING"
    SNAPSHOT_ACCOUNT_NAV_EMPTY = "SNAPSHOT_ACCOUNT_NAV_EMPTY"
    SNAPSHOT_ID_DUPLICATE = "SNAPSHOT_ID_DUPLICATE"
    SNAPSHOT_HISTORY_CREATED = "SNAPSHOT_HISTORY_CREATED"
    SNAPSHOT_HISTORY_APPENDED = "SNAPSHOT_HISTORY_APPENDED"
    SNAPSHOT_DASHBOARD_SUMMARY_MISSING = "SNAPSHOT_DASHBOARD_SUMMARY_MISSING"
    SNAPSHOT_PROVIDER_SUMMARY_MISSING = "SNAPSHOT_PROVIDER_SUMMARY_MISSING"
    SNAPSHOT_WARNINGS_PRESENT = "SNAPSHOT_WARNINGS_PRESENT"
    SNAPSHOT_MIXED_AS_OF_DATES = "SNAPSHOT_MIXED_AS_OF_DATES"
    SNAPSHOT_MIXED_CURRENCY_NAV = "SNAPSHOT_MIXED_CURRENCY_NAV"
    SNAPSHOT_STALE_INPUT_WARNING = "SNAPSHOT_STALE_INPUT_WARNING"
    SNAPSHOT_GENERATED_OK = "SNAPSHOT_GENERATED_OK"
    SNAPSHOT_GENERATED_WITH_WARNINGS = "SNAPSHOT_GENERATED_WITH_WARNINGS"
    PROPERTY_MORTGAGE_INPUT_MISSING = "PROPERTY_MORTGAGE_INPUT_MISSING"
    PROPERTY_INPUT_EMPTY = "PROPERTY_INPUT_EMPTY"
    PROPERTY_REQUIRED_FIELD_MISSING = "PROPERTY_REQUIRED_FIELD_MISSING"
    PROPERTY_OWNERSHIP_MISSING = "PROPERTY_OWNERSHIP_MISSING"
    PROPERTY_VALUATION_MISSING = "PROPERTY_VALUATION_MISSING"
    PROPERTY_VALUATION_STALE = "PROPERTY_VALUATION_STALE"
    PROPERTY_MORTGAGE_REVIEW_REQUIRED = "PROPERTY_MORTGAGE_REVIEW_REQUIRED"
    MORTGAGE_INPUT_EMPTY = "MORTGAGE_INPUT_EMPTY"
    MORTGAGE_REQUIRED_FIELD_MISSING = "MORTGAGE_REQUIRED_FIELD_MISSING"
    MORTGAGE_UNLINKED = "MORTGAGE_UNLINKED"
    MORTGAGE_PROPERTY_LINK_MISSING = "MORTGAGE_PROPERTY_LINK_MISSING"
    PROPERTY_MORTGAGE_GENERATED_OK = "PROPERTY_MORTGAGE_GENERATED_OK"
    PROPERTY_MORTGAGE_GENERATED_WITH_WARNINGS = (
        "PROPERTY_MORTGAGE_GENERATED_WITH_WARNINGS"
    )
    PROPERTY_MORTGAGE_FAILED = "PROPERTY_MORTGAGE_FAILED"
    CPF_SNAPSHOT_MISSING = "CPF_SNAPSHOT_MISSING"
    CPF_BALANCE_MISSING = "CPF_BALANCE_MISSING"
    CPF_REVIEW_REQUIRED = "CPF_REVIEW_REQUIRED"
    SRS_SNAPSHOT_MISSING = "SRS_SNAPSHOT_MISSING"
    SRS_BALANCE_MISSING = "SRS_BALANCE_MISSING"
    SRS_TAX_WRAPPER_REVIEW = "SRS_TAX_WRAPPER_REVIEW"
    TAX_SNAPSHOT_MISSING = "TAX_SNAPSHOT_MISSING"
    TAX_DATA_INCOMPLETE = "TAX_DATA_INCOMPLETE"
    TAX_REVIEW_REQUIRED = "TAX_REVIEW_REQUIRED"
    HDB_LOAN_SNAPSHOT_MISSING = "HDB_LOAN_SNAPSHOT_MISSING"
    HDB_LOAN_BALANCE_MISSING = "HDB_LOAN_BALANCE_MISSING"
    HDB_LOAN_PROPERTY_LINK_MISSING = "HDB_LOAN_PROPERTY_LINK_MISSING"
    SG_SNAPSHOT_GENERATED_OK = "SG_SNAPSHOT_GENERATED_OK"
    SG_SNAPSHOT_GENERATED_WITH_WARNINGS = "SG_SNAPSHOT_GENERATED_WITH_WARNINGS"
    DASHBOARD_V3_INPUT_MISSING = "DASHBOARD_V3_INPUT_MISSING"
    DASHBOARD_V3_MERGE_LEDGER_MISSING = "DASHBOARD_V3_MERGE_LEDGER_MISSING"
    DASHBOARD_V3_SNAPSHOT_HISTORY_MISSING = "DASHBOARD_V3_SNAPSHOT_HISTORY_MISSING"
    DASHBOARD_V3_SNAPSHOT_HISTORY_EMPTY = "DASHBOARD_V3_SNAPSHOT_HISTORY_EMPTY"
    DASHBOARD_V3_DASHBOARD_V2_SUMMARY_MISSING = (
        "DASHBOARD_V3_DASHBOARD_V2_SUMMARY_MISSING"
    )
    DASHBOARD_V3_PROPERTY_SNAPSHOT_MISSING = "DASHBOARD_V3_PROPERTY_SNAPSHOT_MISSING"
    DASHBOARD_V3_SG_SNAPSHOT_MISSING = "DASHBOARD_V3_SG_SNAPSHOT_MISSING"
    DASHBOARD_V3_MIXED_CURRENCY_NAV = "DASHBOARD_V3_MIXED_CURRENCY_NAV"
    DASHBOARD_V3_FX_RATE_MISSING = "DASHBOARD_V3_FX_RATE_MISSING"
    DASHBOARD_V3_FX_NORMALIZATION_APPLIED = "DASHBOARD_V3_FX_NORMALIZATION_APPLIED"
    DASHBOARD_V3_REVIEW_REQUIRED = "DASHBOARD_V3_REVIEW_REQUIRED"
    DASHBOARD_V3_GENERATED_OK = "DASHBOARD_V3_GENERATED_OK"
    DASHBOARD_V3_GENERATED_WITH_WARNINGS = "DASHBOARD_V3_GENERATED_WITH_WARNINGS"
    PRIVATE_INPUT_KIT_INITIALIZED = "PRIVATE_INPUT_KIT_INITIALIZED"
    PRIVATE_INPUT_OVERWRITE_USED = "PRIVATE_INPUT_OVERWRITE_USED"
    PRIVATE_INPUT_FILE_EXISTS_SKIPPED = "PRIVATE_INPUT_FILE_EXISTS_SKIPPED"
    PRIVATE_INPUT_FILE_MISSING = "PRIVATE_INPUT_FILE_MISSING"
    PRIVATE_INPUT_SCHEMA_INVALID = "PRIVATE_INPUT_SCHEMA_INVALID"
    PRIVATE_INPUT_REQUIRED_FIELD_MISSING = "PRIVATE_INPUT_REQUIRED_FIELD_MISSING"
    PRIVATE_INPUT_OPTIONAL_FIELD_MISSING = "PRIVATE_INPUT_OPTIONAL_FIELD_MISSING"
    PRIVATE_INPUT_RAW_IDENTIFIER_DETECTED = "PRIVATE_INPUT_RAW_IDENTIFIER_DETECTED"
    PRIVATE_INPUT_VALIDATION_OK = "PRIVATE_INPUT_VALIDATION_OK"
    PRIVATE_INPUT_VALIDATION_WITH_WARNINGS = "PRIVATE_INPUT_VALIDATION_WITH_WARNINGS"
    PRIVATE_INPUT_VALIDATION_FAILED = "PRIVATE_INPUT_VALIDATION_FAILED"
    PRIVATE_INPUT_CHAIN_GENERATED_OK = "PRIVATE_INPUT_CHAIN_GENERATED_OK"
    PRIVATE_INPUT_CHAIN_GENERATED_WITH_WARNINGS = (
        "PRIVATE_INPUT_CHAIN_GENERATED_WITH_WARNINGS"
    )
    PRIVATE_INPUT_CHAIN_FAILED = "PRIVATE_INPUT_CHAIN_FAILED"
    MANUAL_NAV_FORM_GENERATED = "MANUAL_NAV_FORM_GENERATED"
    MANUAL_NAV_INPUT_INITIALIZED = "MANUAL_NAV_INPUT_INITIALIZED"
    MANUAL_NAV_INPUT_EXISTS_SKIPPED = "MANUAL_NAV_INPUT_EXISTS_SKIPPED"
    MANUAL_NAV_OVERWRITE_USED = "MANUAL_NAV_OVERWRITE_USED"
    MANUAL_NAV_INPUT_MISSING = "MANUAL_NAV_INPUT_MISSING"
    MANUAL_NAV_SCHEMA_INVALID = "MANUAL_NAV_SCHEMA_INVALID"
    MANUAL_NAV_REQUIRED_FIELD_MISSING = "MANUAL_NAV_REQUIRED_FIELD_MISSING"
    MANUAL_NAV_OPTIONAL_SPLIT_MISSING = "MANUAL_NAV_OPTIONAL_SPLIT_MISSING"
    MANUAL_NAV_HASH_SALT_MISSING = "MANUAL_NAV_HASH_SALT_MISSING"
    MANUAL_NAV_RAW_IDENTIFIER_DETECTED = "MANUAL_NAV_RAW_IDENTIFIER_DETECTED"
    MANUAL_NAV_MIXED_CURRENCIES = "MANUAL_NAV_MIXED_CURRENCIES"
    MANUAL_NAV_VALIDATION_OK = "MANUAL_NAV_VALIDATION_OK"
    MANUAL_NAV_VALIDATION_WITH_WARNINGS = "MANUAL_NAV_VALIDATION_WITH_WARNINGS"
    MANUAL_NAV_VALIDATION_FAILED = "MANUAL_NAV_VALIDATION_FAILED"
    MANUAL_NAV_BUNDLE_GENERATED_OK = "MANUAL_NAV_BUNDLE_GENERATED_OK"
    MANUAL_NAV_BUNDLE_GENERATED_WITH_WARNINGS = (
        "MANUAL_NAV_BUNDLE_GENERATED_WITH_WARNINGS"
    )
    MANUAL_NAV_BUNDLE_FAILED = "MANUAL_NAV_BUNDLE_FAILED"
    PRIVATE_INPUT_CENTER_FORM_GENERATED = "PRIVATE_INPUT_CENTER_FORM_GENERATED"
    PRIVATE_INPUT_CENTER_INITIALIZED = "PRIVATE_INPUT_CENTER_INITIALIZED"
    PRIVATE_INPUT_CENTER_EXISTS_SKIPPED = "PRIVATE_INPUT_CENTER_EXISTS_SKIPPED"
    PRIVATE_INPUT_CENTER_OVERWRITE_USED = "PRIVATE_INPUT_CENTER_OVERWRITE_USED"
    PRIVATE_INPUT_CENTER_INPUT_MISSING = "PRIVATE_INPUT_CENTER_INPUT_MISSING"
    PRIVATE_INPUT_CENTER_SCHEMA_INVALID = "PRIVATE_INPUT_CENTER_SCHEMA_INVALID"
    PRIVATE_INPUT_CENTER_REQUIRED_FIELD_MISSING = (
        "PRIVATE_INPUT_CENTER_REQUIRED_FIELD_MISSING"
    )
    PRIVATE_INPUT_CENTER_OPTIONAL_FIELD_MISSING = (
        "PRIVATE_INPUT_CENTER_OPTIONAL_FIELD_MISSING"
    )
    PRIVATE_INPUT_CENTER_RAW_IDENTIFIER_DETECTED = (
        "PRIVATE_INPUT_CENTER_RAW_IDENTIFIER_DETECTED"
    )
    PRIVATE_INPUT_CENTER_VALIDATION_OK = "PRIVATE_INPUT_CENTER_VALIDATION_OK"
    PRIVATE_INPUT_CENTER_VALIDATION_WITH_WARNINGS = (
        "PRIVATE_INPUT_CENTER_VALIDATION_WITH_WARNINGS"
    )
    PRIVATE_INPUT_CENTER_VALIDATION_FAILED = "PRIVATE_INPUT_CENTER_VALIDATION_FAILED"
    PRIVATE_INPUT_CENTER_GENERATED_OK = "PRIVATE_INPUT_CENTER_GENERATED_OK"
    PRIVATE_INPUT_CENTER_GENERATED_WITH_WARNINGS = (
        "PRIVATE_INPUT_CENTER_GENERATED_WITH_WARNINGS"
    )
    PRIVATE_INPUT_CENTER_GENERATION_FAILED = "PRIVATE_INPUT_CENTER_GENERATION_FAILED"
    NET_WORTH_REFRESH_GENERATED_OK = "NET_WORTH_REFRESH_GENERATED_OK"
    NET_WORTH_REFRESH_GENERATED_WITH_WARNINGS = (
        "NET_WORTH_REFRESH_GENERATED_WITH_WARNINGS"
    )
    NET_WORTH_REFRESH_FAILED = "NET_WORTH_REFRESH_FAILED"
    NET_WORTH_REFRESH_LIVE_READ_SKIPPED = "NET_WORTH_REFRESH_LIVE_READ_SKIPPED"
    NET_WORTH_REFRESH_BROKER_READ_FAILED = "NET_WORTH_REFRESH_BROKER_READ_FAILED"
    NET_WORTH_REFRESH_SNAPSHOT_PENDING_REVIEW = (
        "NET_WORTH_REFRESH_SNAPSHOT_PENDING_REVIEW"
    )
    NET_WORTH_REFRESH_SNAPSHOT_HISTORY_CONFIRMED = (
        "NET_WORTH_REFRESH_SNAPSHOT_HISTORY_CONFIRMED"
    )
    NET_WORTH_DOCTOR_INPUT_MISSING = "NET_WORTH_DOCTOR_INPUT_MISSING"
    NET_WORTH_DOCTOR_INPUT_INVALID = "NET_WORTH_DOCTOR_INPUT_INVALID"
    NET_WORTH_DOCTOR_REFRESH_MISSING = "NET_WORTH_DOCTOR_REFRESH_MISSING"
    NET_WORTH_DOCTOR_REFRESH_INCOMPLETE = "NET_WORTH_DOCTOR_REFRESH_INCOMPLETE"
    NET_WORTH_DOCTOR_FX_MISSING = "NET_WORTH_DOCTOR_FX_MISSING"
    NET_WORTH_DOCTOR_FX_INCOMPLETE = "NET_WORTH_DOCTOR_FX_INCOMPLETE"
    NET_WORTH_DOCTOR_BROKER_CONFIG_MISSING = (
        "NET_WORTH_DOCTOR_BROKER_CONFIG_MISSING"
    )
    NET_WORTH_DOCTOR_GENERATED_OK = "NET_WORTH_DOCTOR_GENERATED_OK"
    NET_WORTH_DOCTOR_GENERATED_WITH_WARNINGS = (
        "NET_WORTH_DOCTOR_GENERATED_WITH_WARNINGS"
    )
    DATA_QUALITY_REFRESH_INCOMPLETE = "DATA_QUALITY_REFRESH_INCOMPLETE"
    DATA_QUALITY_BROKER_FAILURES = "DATA_QUALITY_BROKER_FAILURES"
    DATA_QUALITY_FX_INCOMPLETE = "DATA_QUALITY_FX_INCOMPLETE"
    DATA_QUALITY_STALE_OR_MIXED_DATES = "DATA_QUALITY_STALE_OR_MIXED_DATES"
    DATA_QUALITY_EXPECTED_SOURCE_MISSING = "DATA_QUALITY_EXPECTED_SOURCE_MISSING"
    DATA_QUALITY_GENERATED_OK = "DATA_QUALITY_GENERATED_OK"
    DATA_QUALITY_GENERATED_WITH_WARNINGS = "DATA_QUALITY_GENERATED_WITH_WARNINGS"
    EXPECTED_SOURCE_CONTRACT_INVALID = "EXPECTED_SOURCE_CONTRACT_INVALID"
    EXPECTED_SOURCE_REQUIRED_MISSING = "EXPECTED_SOURCE_REQUIRED_MISSING"
    INTEGRITY_GUARD_OK = "INTEGRITY_GUARD_OK"
    INTEGRITY_GUARD_BLOCKED = "INTEGRITY_GUARD_BLOCKED"
    INTEGRITY_EXPECTED_SOURCE_MISSING = "INTEGRITY_EXPECTED_SOURCE_MISSING"
    INTEGRITY_BROKER_REQUESTED_MISSING = "INTEGRITY_BROKER_REQUESTED_MISSING"
    INTEGRITY_PROVIDER_NAV_MISSING = "INTEGRITY_PROVIDER_NAV_MISSING"
    INTEGRITY_TOTAL_NAV_UNAVAILABLE = "INTEGRITY_TOTAL_NAV_UNAVAILABLE"
    INTEGRITY_MIXED_CURRENCY_BLOCKED = "INTEGRITY_MIXED_CURRENCY_BLOCKED"
    INTEGRITY_FX_REQUIRED = "INTEGRITY_FX_REQUIRED"
    INTEGRITY_MIXED_AS_OF_DATES = "INTEGRITY_MIXED_AS_OF_DATES"
    INTEGRITY_STALE_PROVIDER_DATA = "INTEGRITY_STALE_PROVIDER_DATA"
    INTEGRITY_SNAPSHOT_PENDING_REVIEW = "INTEGRITY_SNAPSHOT_PENDING_REVIEW"
    INTEGRITY_CONFIRMED_HISTORY_MISSING = "INTEGRITY_CONFIRMED_HISTORY_MISSING"
    INTEGRITY_NAV_CHANGE_REVIEW_REQUIRED = "INTEGRITY_NAV_CHANGE_REVIEW_REQUIRED"
    SNAPSHOT_HISTORY_MANAGER_INPUT_MISSING = "SNAPSHOT_HISTORY_MANAGER_INPUT_MISSING"
    SNAPSHOT_HISTORY_MANAGER_NO_HISTORY_ROWS = "SNAPSHOT_HISTORY_MANAGER_NO_HISTORY_ROWS"
    SNAPSHOT_HISTORY_MANAGER_KEEP_SET_EMPTY = "SNAPSHOT_HISTORY_MANAGER_KEEP_SET_EMPTY"
    SNAPSHOT_HISTORY_MANAGER_DRY_RUN = "SNAPSHOT_HISTORY_MANAGER_DRY_RUN"
    SNAPSHOT_HISTORY_MANAGER_BACKUP_CREATED = "SNAPSHOT_HISTORY_MANAGER_BACKUP_CREATED"
    SNAPSHOT_HISTORY_MANAGER_APPLIED = "SNAPSHOT_HISTORY_MANAGER_APPLIED"
    SNAPSHOT_HISTORY_MANAGER_GENERATED_OK = "SNAPSHOT_HISTORY_MANAGER_GENERATED_OK"
    SNAPSHOT_HISTORY_MANAGER_GENERATED_WITH_WARNINGS = (
        "SNAPSHOT_HISTORY_MANAGER_GENERATED_WITH_WARNINGS"
    )
    SNAPSHOT_REVIEW_READY_TO_CONFIRM = "SNAPSHOT_REVIEW_READY_TO_CONFIRM"
    SNAPSHOT_REVIEW_BLOCKED = "SNAPSHOT_REVIEW_BLOCKED"
    LOCAL_WORKBENCH_INPUT_MISSING = "LOCAL_WORKBENCH_INPUT_MISSING"
    LOCAL_WORKBENCH_REFRESH_MISSING = "LOCAL_WORKBENCH_REFRESH_MISSING"
    LOCAL_WORKBENCH_FX_MISSING = "LOCAL_WORKBENCH_FX_MISSING"
    LOCAL_WORKBENCH_GENERATED_OK = "LOCAL_WORKBENCH_GENERATED_OK"
    LOCAL_WORKBENCH_GENERATED_WITH_WARNINGS = (
        "LOCAL_WORKBENCH_GENERATED_WITH_WARNINGS"
    )
    DASHBOARD_V4_INPUT_MISSING = "DASHBOARD_V4_INPUT_MISSING"
    DASHBOARD_V4_BUCKET_CLASSIFICATION_WARNING = (
        "DASHBOARD_V4_BUCKET_CLASSIFICATION_WARNING"
    )
    DASHBOARD_V4_UNCLASSIFIED_ASSETS = "DASHBOARD_V4_UNCLASSIFIED_ASSETS"
    DASHBOARD_V4_FX_RATES_MISSING = "DASHBOARD_V4_FX_RATES_MISSING"
    DASHBOARD_V4_FX_CONVERSION_SKIPPED = "DASHBOARD_V4_FX_CONVERSION_SKIPPED"
    DASHBOARD_V4_BUCKET_HISTORY_LIMITED = "DASHBOARD_V4_BUCKET_HISTORY_LIMITED"
    DASHBOARD_V4_WITHDRAWAL_CASHFLOW_GENERATED = (
        "DASHBOARD_V4_WITHDRAWAL_CASHFLOW_GENERATED"
    )
    DASHBOARD_V4_FIRE_TARGET_INPUT_MISSING = (
        "DASHBOARD_V4_FIRE_TARGET_INPUT_MISSING"
    )
    DASHBOARD_V4_FIRE_TARGET_FX_MISSING = "DASHBOARD_V4_FIRE_TARGET_FX_MISSING"
    DASHBOARD_V4_FIRE_TARGET_GENERATED = "DASHBOARD_V4_FIRE_TARGET_GENERATED"
    DASHBOARD_V4_GENERATED_OK = "DASHBOARD_V4_GENERATED_OK"
    DASHBOARD_V4_GENERATED_WITH_WARNINGS = "DASHBOARD_V4_GENERATED_WITH_WARNINGS"


LEDGER_FIELDNAMES = [
    "provider",
    "account_id_hash",
    "asset_id",
    "asset_type",
    "symbol",
    "name",
    "quantity",
    "currency",
    "market_value",
    "cost_basis",
    "unrealized_pnl",
    "liquidity_bucket",
    "risk_bucket",
    "source_timestamp",
    "source_confidence",
    "needs_review",
    "warning_codes",
    "notes",
]


@dataclass(frozen=True)
class ProviderStatus:
    provider_name: str
    provider_level: ProviderLevel
    connection_mode: ConnectionMode
    read_only: bool = True
    trading_enabled: bool = False
    order_placement_enabled: bool = False
    credentials_source: str = "environment_variables"
    last_sync_time: str | None = None
    warning_codes: list[WarningCode] = field(default_factory=list)
    raw_snapshot_path: str | None = None
    normalized_positions: list[dict[str, Any]] = field(default_factory=list)
    diagnostics: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        payload = {
            "provider_name": self.provider_name,
            "provider_level": self.provider_level.value,
            "connection_mode": self.connection_mode.value,
            "read_only": self.read_only,
            "trading_enabled": self.trading_enabled,
            "order_placement_enabled": self.order_placement_enabled,
            "credentials_source": self.credentials_source,
            "last_sync_time": self.last_sync_time,
            "warning_codes": [code.value for code in self.warning_codes],
            "raw_snapshot_path": self.raw_snapshot_path,
            "normalized_positions": self.normalized_positions,
        }
        if self.diagnostics:
            payload["diagnostics"] = self.diagnostics
        return payload


@dataclass(frozen=True)
class RawAccount:
    account_id: str
    account_type: str = "unknown"
    currency: str | None = None
    notes: str = ""


@dataclass(frozen=True)
class RawCash:
    account_id: str
    currency: str
    amount: float
    source_timestamp: str
    notes: str = ""


@dataclass(frozen=True)
class RawPosition:
    account_id: str
    asset_id: str
    asset_type: str
    symbol: str
    name: str
    quantity: float
    currency: str | None
    market_value: float | None
    cost_basis: float | None = None
    unrealized_pnl: float | None = None
    liquidity_bucket: str = "unknown"
    risk_bucket: str = "unknown"
    source_timestamp: str = ""
    source_confidence: str = "manual"
    needs_review: bool = False
    warning_codes: list[WarningCode] = field(default_factory=list)
    notes: str = ""


@dataclass(frozen=True)
class RawBalance:
    account_id: str
    asset_id: str
    asset_type: str
    name: str
    currency: str | None
    amount: float | None
    source_timestamp: str
    liquidity_bucket: str = "liability"
    risk_bucket: str = "liability"
    source_confidence: str = "manual"
    needs_review: bool = False
    warning_codes: list[WarningCode] = field(default_factory=list)
    notes: str = ""


@dataclass(frozen=True)
class RawProviderSnapshot:
    provider_name: str
    status: ProviderStatus
    accounts: list[RawAccount] = field(default_factory=list)
    cash: list[RawCash] = field(default_factory=list)
    positions: list[RawPosition] = field(default_factory=list)
    balances: list[RawBalance] = field(default_factory=list)

    def has_data(self) -> bool:
        return bool(self.accounts or self.cash or self.positions or self.balances)


@dataclass(frozen=True)
class NormalizedAsset:
    provider: str
    account_id_hash: str
    asset_id: str
    asset_type: str
    symbol: str
    name: str
    quantity: float | None
    currency: str | None
    market_value: float | None
    cost_basis: float | None
    unrealized_pnl: float | None
    liquidity_bucket: str
    risk_bucket: str
    source_timestamp: str
    source_confidence: str
    needs_review: bool
    warning_codes: list[WarningCode]
    notes: str = ""

    def to_csv_row(self) -> dict[str, str]:
        return {
            "provider": self.provider,
            "account_id_hash": self.account_id_hash,
            "asset_id": self.asset_id,
            "asset_type": self.asset_type,
            "symbol": self.symbol,
            "name": self.name,
            "quantity": _stringify_number(self.quantity),
            "currency": self.currency or "",
            "market_value": _stringify_number(self.market_value),
            "cost_basis": _stringify_number(self.cost_basis),
            "unrealized_pnl": _stringify_number(self.unrealized_pnl),
            "liquidity_bucket": self.liquidity_bucket,
            "risk_bucket": self.risk_bucket,
            "source_timestamp": self.source_timestamp,
            "source_confidence": self.source_confidence,
            "needs_review": str(self.needs_review).lower(),
            "warning_codes": ";".join(code.value for code in self.warning_codes),
            "notes": self.notes,
        }


@dataclass(frozen=True)
class RiskSummary:
    total_assets: float
    total_liabilities: float
    net_worth: float
    liquid_assets: float
    investable_assets: float
    provider_coverage_ratio: float
    manual_asset_share: float
    currency_exposure: dict[str, float]
    warning_codes: list[WarningCode]


def _stringify_number(value: float | None) -> str:
    if value is None:
        return ""
    return f"{value:.2f}"
